---
- name: Create multi-node Kind cluster
  hosts: localhost
  vars:
    ClusterName: multi-node-cluster
  tasks:
    - name: Create Kind configuration
      ansible.builtin.copy:
        dest: /home/pronojit/DevOpsStudy/1.Cluster/kind-config.yaml
        content: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
          - role: worker
            kubeadmConfigPatches:
            - |
              kind: JoinConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  node-labels: "env=test"
                  register-with-taints: "env=test:NoSchedule"
          - role: worker
            kubeadmConfigPatches:
            - |
              kind: JoinConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  node-labels: "env=dev"
                  register-with-taints: "env=dev:NoSchedule"


    - name: Delete Kind cluster
      ansible.builtin.command: kind delete clusters "{{ ClusterName }}"

    - name: Delete old .kube/config
      file:
        path: /home/pronojit/.kube/config
        state: absent

    - name: Create Kind cluster
      ansible.builtin.command: kind create cluster --config=/home/pronojit/DevOpsStudy/1.Cluster/kind-config.yaml --name="{{ ClusterName }}"

    - name: Set kubectl context
      ansible.builtin.command: kubectl cluster-info --context  kind-"{{ ClusterName }}"
      register: set_context_result

    - name: Display cluster info
      ansible.builtin.command: kubectl cluster-info
      register: cluster_info_result

    - name: Display command output
      debug:
        var: cluster_info_result.stdout

    - name: Copy /home/pronojit/.kube/config
      command: cp /home/pronojit/.kube/config /mnt/c/Users/pronojit.roy/.kube/config

