---
- name: Create ClusterRole for Access to Resources
  hosts: localhost
  vars_files:
    - values.yaml
  tasks:
    - name: Create ClusterRole
      k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: "{{ClusterRole}}"
          rules:
            - apiGroups: ["*"]
              resources: ["pods", "services", "deployments", "statefulsets", "secrets", "configmaps", "ingresses", "jobs"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
