---
- name: Create ClusterRoleBinding
  hosts: localhost
  tasks:
    - name: Create ClusterRoleBinding YAML
      copy:
        dest: /home/pronojit/DevOpsStudy/1.Cluster/cluster_role_binding.yaml
        content: |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: developer-access-binding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: developer-access
          subjects:
            - kind: User
              name: user.d


    - name: Apply ClusterRoleBinding
      ansible.builtin.command: kubectl apply -f /home/pronojit/DevOpsStudy/1.Cluster/cluster_role_binding.yaml  





