---
- name: Create Role for Namespace
  hosts: localhost
  vars_files:
    - values.yaml
  tasks:
    - name: Create Role
      k8s:
        api_version: rbac.authorization.k8s.io/v1
        kind: Role
        name: "{{ ServiceAccountRole }}"
        namespace: "{{ NameSpace }}"
        resource_definition: |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: {{ ServiceAccountRole }}
          rules:
            - apiGroups: ["*"]
              resources: ["pods", "services", "deployments", "statefulsets", "secrets", "configmaps", "ingresses", "jobs"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
        state: present
